#
# This file is part of cgrc.
#
# Copyright (c) 2022 Luca Carlon
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_qt5
  - test_qt6
  - test_rust
  - build_rust

Test_qt5:
  stage: test_qt5
  image:
    name: "carlonluca/qt-dev:5.15.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./cgrc --version

Test_qt6:
  stage: test_qt6
  image:
    name: "carlonluca/qt-dev:6.3.1_jammy"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./cgrc --version

Test_rust:
  stage: test_rust
  image:
    name: "rust:1.69"
  script:
    - cd cgrc-rust
    - cargo build

Build:
  stage: build_rust
  image:
    name: "rust:1.69"
  artifacts:
    paths:
      - cgrc-dist/x86_64-unknown-linux-musl/cgrc
    untracked: true
  script:
    - cd cgrc-rust
    - rustup target add x86_64-unknown-linux-musl
    - cargo build --release --target=x86_64-unknown-linux-musl
    - mkdir -p ../cgrc-dist/x86_64-unknown-linux-musl
    - mv target/x86_64-unknown-linux-musl/release/cgrc ../cgrc-dist/x86_64-unknown-linux-musl/