name: cgrc
version: '0.3.2'
grade: devel
base: core20
confinement: strict
summary: Configurable terminal text formatter
description: |
  cgrc formats text from stdin according to custom configuration files
  and outputs the result with ANSI escape codes to stdout. Configuration
  files includes a set of regular expressions with the related format
  to be used to the match and the captures.
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  cgrc:
    command: usr/bin/cgrc

parts:
  cgrc:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    source-type: git
    source-branch: master
    source: https://github.com/carlonluca/cgrc.git
    build-packages:
      - g++
      - cmake
      - qt6-tools-dev
    stage-packages:
      - libc6
      - libstdc++6
      - libqt6core6
