name: cgrc
version: '0.3.1'
grade: devel
base: core20
summary: cgrc
description: "A generic formatter for logs"
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  cgrc:
    command: usr/bin/cgrc

parts:
  cgrc:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    source-type: git
    source-tag: v0.3.1
    source: https://github.com/carlonluca/cgrc.git
    build-packages:
      - g++
      - cmake
      - qt5-default
    stage-packages:
      - libc6
      - libstdc++6
      - libqt5core5a
