name: cgrc
version: '2.0.1'
grade: devel
base: core18
confinement: strict
summary: Configurable terminal text formatter
description: |
  cgrc formats text from stdin according to custom configuration files
  and outputs the result with ANSI escape codes to stdout. Configuration
  files includes a set of regular expressions with the related format
  to be used to the match and the captures.
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  cgrc:
    command: bin/cgrc

parts:
  cgrc:
    plugin: rust
    source-type: git
    source-subdir: cgrc-rust
    source-branch: master
    source: https://github.com/carlonluca/cgrc.git
