name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/carlonluca/qt-dev:6.3.1_jammy
    steps:
      - name: build
        shell: bash
        run: |
          ls -l
          cd cgrc
          ls -l
          mkdir build
          cd build
          cmake ..
          make
          ./cgrc --version